using Inventory_Management_System.Database;
using Microsoft.EntityFrameworkCore;
using ModelContextProtocol.Server;
using System.ComponentModel;
using System.Text.Json;

namespace Inventory_Management_System.Shared.McpTools
{
    [McpServerToolType]
    public class DatabaseMcpTools
    {
        private readonly AppDbContext _dbContext;
        public DatabaseMcpTools(AppDbContext context)
        {
            _dbContext = context;
        }

        [McpServerTool(Name = "execute_readonly_sql")]
        [Description("Executes a read-only SQL query against the PostgreSQL database(use all case of table name) and returns the results. Use this for complex reporting or custom filters.")]
        public async Task<string> ExecuteQueryAsync(string sqlQuery)
        {
            // WARNING: This executes raw SQL generated by the LLM
            using var command = _dbContext.Database.GetDbConnection().CreateCommand();
            command.CommandText = sqlQuery;

            _dbContext.Database.OpenConnection();
            using var result = await command.ExecuteReaderAsync();
            return JsonSerializer.Serialize(result);

        }
    }
}
